config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/create'
  get 'cart_items/update'
  get 'cart_items/destroy'
  get 'carts/show'
  get 'products/index'
  get 'products/show'
  # devise_for :users, controllers: { registrations: 'registrations' }

  resources :products, only: %i[index show]
  resources :cart_items, only: %i[index create update destroy]

  root 'products#index'

  get 'search', to: 'pages#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  def total_items
    cart_items.to_a.sum { |item| item.quantity }
  end

  def total_price
    cart_items.to_a.sum { |item| item.total_price }
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items
  has_many :carts, through: :cart_items

  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  def gravatar_url
    hash = Digest::MD5.hexdigest(email.downcase)
    "https://secure.gravatar.com/avatar/#{hash}.png?s=200"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_cart

  private

  def current_cart
    if session[:cart_id]
      @current_cart ||= Cart.includes(:products).find_by(id: session[:cart_id])
      session.delete(:cart_id) if @current_cart.nil? # Handle cases where cart has been deleted
    end
    if session[:cart_id].nil?
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
    @current_cart
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart = current_cart
  end

  def create
    @cart = current_cart
    product = Product.find(params[:product_id])

    # Find existing cart item or create a new one
    @cart_item = @cart.cart_items.find_or_initialize_by(product: product)
    @cart_item.quantity += 1
    @cart_item.save

    respond_to do |format|
      format.html do
        redirect_to products_path, notice: "#{product.name} added to cart."
      end
      format.turbo_stream
    end
  end

  def update
    @cart = current_cart
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart = current_cart
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy

    redirect_to cart_items_path(@cart_item.cart)
    # respond_to do |format|
    #   format.html {  }
    #   format.turbo_stream
    # end
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end

  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  private

  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # TO DO - this functionality was started but never completed.
  def search
    query = params[:search]
    if query.present?
      @products = Product.where('LOWER(name) LIKE ?', "%#{search.downcase}%") if search.present?
    else
      @products = Product.all
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @cart = current_cart
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
  def funny_cart_message(item_count)
    case item_count
    when 1
      "First item added! Let's start filling up that cart!"
    when 2..4
      "Nice! You’ve got #{item_count} items in your cart now!"
    when 5..9
      "Whoa, #{item_count} items? Someone’s on a shopping spree!"
    when 10..14
      "Double digits! #{item_count} items in the cart. You’re on fire!"
    when 15..19
      "Wow, #{item_count} items! Maybe take a break? Nah, keep going!"
    else
      "#{item_count} items?! Are you buying out the entire store?"
    end
  end
end

app/views/cart_items/_summary.html.erb
<div class="border my-3 shadow rounded p-3">
    Cart last updated at: <%= Time.now.to_s %>
    <p>Total: <%= number_to_currency(cart.present? ? cart.total_price : "0") %></p>
</div>

app/views/cart_items/create.html.erb
<div>
  <h1 class="font-bold text-4xl">CartItems#create</h1>
  <p>Find me in app/views/cart_items/create.html.erb</p>
</div>

app/views/cart_items/create.turbo_stream.erb
<%= turbo_stream.update "cart_counter" do %>
  <%= @cart.total_items %>
<% end %>

<%= turbo_stream.update "cart_summary" do %>
  <%= render "cart_items/summary", cart: @cart.reload %>
<% end %>

<%= turbo_stream.append "cart_notices" do %>
  <p data-controller="cart-notice confetti" class="mb-3 p-3 border-gray-200 bg-gray-100 rounded-xl">
    <%= funny_cart_message(@cart.total_items) %>
  </p>
<% end %>

app/views/cart_items/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">CartItems#destroy</h1>
  <p>Find me in app/views/cart_items/destroy.html.erb</p>
</div>

app/views/cart_items/index.html.erb
<div class="container mx-auto mt-10">
  <div class="flex shadow-md my-10">
    <div class="w-full bg-white px-10 py-10">
      <div class="flex justify-between border-b pb-8">
        <h1 class="font-semibold text-2xl">Shopping Cart</h1>
        <h2 class="font-semibold text-2xl"><%= pluralize(@cart.cart_items.count, 'Item') %></h2>
      </div>

      <% if @cart.cart_items.any? %>
        <div class="flex mt-10 mb-5">
          <h3 class="font-semibold text-gray-600 text-xs uppercase w-2/5">Product Details</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5">Quantity</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5">Price</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5">Total</h3>
        </div>

        <% @cart.cart_items.each do |item| %>
          <div class="flex items-center hover:bg-gray-100 -mx-8 px-6 py-5">
            <div class="flex w-2/5">
              <div class="w-20">
                <!-- Placeholder image - replace with actual product image if available -->
                <img class="h-24" src="https://via.placeholder.com/150" alt="<%= item.product.name %>">
              </div>
              <div class="flex flex-col justify-between ml-4 flex-grow">
                <span class="font-bold text-sm"><%= link_to item.product.name, product_path(item.product) %></span>
                <%= button_to 'Remove', cart_item_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: "font-semibold hover:text-red-500 text-gray-500 text-xs" %>
              </div>
            </div>
            <div class="flex justify-center w-1/5">
              <span class="text-center w-1/5 font-semibold text-sm"><%= item.quantity %></span>
            </div>
            <span class="text-center w-1/5 font-semibold text-sm"><%= number_to_currency(item.product.price) %></span>
            <span class="text-center w-1/5 font-semibold text-sm"><%= number_to_currency(item.total_price) %></span>
          </div>
        <% end %>

        <div class="flex justify-between mt-10">
          <%= link_to 'Continue Shopping', products_path, class: "font-semibold text-indigo-600 text-sm" %>
          <span class="text-right text-xl font-semibold">Total: <%= number_to_currency(@cart.total_price) %></span>
        </div>
      <% else %>
        <p class="text-center text-lg">Your cart is empty.</p>
        <div class="flex justify-center mt-10">
          <%= link_to 'Start Shopping', products_path, class: "font-semibold bg-indigo-600 text-white py-2 px-4 rounded-md" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cart_items/update.html.erb
<div>
  <h1 class="font-bold text-4xl">CartItems#update</h1>
  <p>Find me in app/views/cart_items/update.html.erb</p>
</div>

app/views/layouts/_alerts.html.erb
<!-- ========== ALERTS ========== -->
<div class="container m-auto">
  <div class="w-full">
    <% if notice %>
      <div class="m-3">
        <div class="alert alert-success" role="alert">
          <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z" /><path d="m9 12 2 2 4-4" /></svg>
          <span><%= notice %></span>
        </div>
      </div>
    <% end %>
    <% if alert %>
      <div class="m-3">
        <div class="alert alert-error" role="alert">
          <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18" /><path d="m6 6 12 12" /></svg>
          <span><%= alert %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- ========== END ALERTS ========== -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FISH STORE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
    <link rel="manifest" href="/manifest.json">

    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.3.0/dist/confetti.browser.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/marketing/navbar' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
    <%= render 'layouts/marketing/footer' %>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<!-- <div class="group flex items-center gap-x-3 border-b border-gray-200 pb-8 mb-8 dark:border-gray-700"></div>
<div class="flex justify-end">
  <a href="<%= new_model_definition_path %>">
    <button type="button" class="py-1.5 px-2.5 inline-flex items-center gap-x-2 text-xs font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600">
      <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" x2="19" y1="8" y2="14"/><line x1="22" x2="16" y1="11" y2="11"/></svg>
      New ModelDefinition
    </button>
  </a>
</div>-->
<div class="navbar rounded-lg bg-base-100">
  <div class="flex-1">
    <a class="btn btn-ghost text-xl">Slip ZapiApp</a>
  </div>
  <div class="flex-none">
    <div data-controller="dropdown">
      <div class="flex justify-end">
        <button data-action="click->dropdown#toggleMenu" class="btn btn-square btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
        </button>
      </div>

      <div data-dropdown-target="menu" class="hidden min-w-[15rem] bg-white shadow-md rounded-lg p-2 mt-2 dark:bg-neutral-800 dark:border dark:border-neutral-700">
        <div class="group flex items-center gap-x-3 -m-2 bg-neutral-100 rounded-t-lg dark:bg-neutral-700">
          <div class="py-3 px-2">
            <img class="h-10 w-10 rounded-full" src="<%= current_user.gravatar_url %>" alt="Profile Gravatar Linking to Profile">
          </div>
          <div class="py-3 ps-1 pe-3">
            <p class="text-sm text-neutral-500 dark:text-neutral-400">Signed in as</p>
            <p class="text-sm font-medium text-neutral-800 dark:text-neutral-300">
              <%= current_user.email %>
            </p>
          </div>
        </div>
        <div class="mt-2 py-2 first:pt-0 last:pb-0">
          <!--<a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-neutral-800 hover:bg-neutral-100 focus:outline-none focus:bg-neutral-100 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300 dark:focus:bg-neutral-700" href="<%=  %>">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-inbox-fill" viewBox="0 0 16 16">
              <path d="M4.98 4a.5.5 0 0 0-.39.188L1.54 8H6a.5.5 0 0 1 .5.5 1.5 1.5 0 1 0 3 0A.5.5 0 0 1 10 8h4.46l-3.05-3.812A.5.5 0 0 0 11.02 4zm-1.17-.437A1.5 1.5 0 0 1 4.98 3h6.04a1.5 1.5 0 0 1 1.17.563l3.7 4.625a.5.5 0 0 1 .106.374l-.39 3.124A1.5 1.5 0 0 1 14.117 13H1.883a1.5 1.5 0 0 1-1.489-1.314l-.39-3.124a.5.5 0 0 1 .106-.374l3.7-4.625z"/>
            </svg>
            ModelDefinitions
          </a>
          <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-neutral-800 hover:bg-neutral-100 focus:outline-none focus:bg-neutral-100 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300 dark:focus:bg-neutral-700" href="<%= sources_path %>">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-link-45deg" viewBox="0 0 16 16">
              <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1.002 1.002 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4.018 4.018 0 0 1-.128-1.287z"/>
              <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243z"/>
            </svg>
            Sources
          </a>-->
          <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-neutral-800 hover:bg-neutral-100 focus:outline-none focus:bg-neutral-100 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300 dark:focus:bg-neutral-700" href="<%= preferences_path(current_user) %>">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill-gear" viewBox="0 0 16 16">
              <path d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0m-9 8c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4m9.886-3.54c.18-.613 1.048-.613 1.229 0l.043.148a.64.64 0 0 0 .921.382l.136-.074c.561-.306 1.175.308.87.869l-.075.136a.64.64 0 0 0 .382.92l.149.045c.612.18.612 1.048 0 1.229l-.15.043a.64.64 0 0 0-.38.921l.074.136c.305.561-.309 1.175-.87.87l-.136-.075a.64.64 0 0 0-.92.382l-.045.149c-.18.612-1.048.612-1.229 0l-.043-.15a.64.64 0 0 0-.921-.38l-.136.074c-.561.305-1.175-.309-.87-.87l.075-.136a.64.64 0 0 0-.382-.92l-.148-.045c-.613-.18-.613-1.048 0-1.229l.148-.043a.64.64 0 0 0 .382-.921l-.074-.136c-.306-.561.308-1.175.869-.87l.136.075a.64.64 0 0 0 .92-.382l.045-.148ZM14 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0"/>
            </svg>
            Account Settings
          </a>
          <%= form_for(:user, url: destroy_user_session_path, method: :delete) do %>
            <button type="submit" class="w-full flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-neutral-800 hover:bg-neutral-100 focus:outline-none focus:bg-neutral-100 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:hover:text-neutral-300 dark:focus:bg-neutral-700">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
              </svg>
              Sign out?
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application/_navdrawer.html.erb
<div class="z-11 flex flex-col bg-base-200 m-2 rounded shadow">
  <div class="z-[100] w-full max-w-[150px] sticky">
    
  </div>
  
  <div class="flex-1">
    <div>
      <ul class="menu text-base-content">
        <!-- Sidebar content here -->
        <li>
          <a href="<%=  %>">
            Models
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="flex-none">
    <ul class="menu text-base-content mt-96">
      <!-- Sidebar content here -->
      <li>
        <a href="<%= preferences_path(current_user) %>">
          Account
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/marketing/_navbar.html.erb
<div class="container mx-auto">
  <div class="navbar">
    <div class="flex-1">
      <a class="btn" href="<%= root_path %>">
        FISH STORE
      </a>
    </div>
    <div class="flex-none gap-2">
      <!-- Cart Button -->
      <%= link_to cart_items_path, class: "relative inline-block text-gray-700" do %>
        <!-- Cart Item Count -->
        <% if @current_cart && @current_cart.cart_items.count > 0 %>
          <span id="cart_counter" class="absolute top-0 right-0 inline-block w-6 h-6 text-center bg-red-600 text-white rounded-full text-sm font-semibold">
            <%= @current_cart.cart_items.sum(:quantity) %>
          </span>
        <% else %>
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5H19m-9 10a2 2 0 110 4 2 2 0 010-4zm8 0a2 2 0 110 4 2 2 0 010-4z"></path>
          </svg>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container products m-auto my-12">
  <div class="flex flex-cols">
    <img src="<%= image_path("cat.webp") %>" class="w-full max-w-[150px]" />
    <div id="cart_notices" class="w-full">
      <div id="cart_summary" class="mb-3 w-full">
        <%= render "cart_items/summary", cart: @cart.reload %>
      </div>
    </div>
  </div>

  <div class="flex flex-cols w-full border shadow-xl rounded-xl overflow-hidden">
    <div>
      <img src="<%= image_path("fish_store_bg.png") %>" class="w-full max-w-[450px]" />
    </div>
    <div class="flex-auto p-6">
      <% @products.each do |product| %>
        <div class="product p-4 rounded-xl shadow-xl border mb-6">
          <div class="grid grid-cols-2">
            <div>
              <h2 class="font-bold font-lg"><%= product.name %></h2>
              <p><%= number_to_currency(product.price) %></p>
            </div>
            <div>
              <%= form_with url: cart_items_path, method: :post, format: :turbo_stream, local: true do %>
                <%= hidden_field_tag :product_id, product.id %>
                <%= submit_tag 'Add to Cart', class: "btn btn-sm btn-block" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Products#show</h1>
  <p>Find me in app/views/products/show.html.erb</p>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t('errors.messages.not_saved',
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase) %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to 'Log in', new_session_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to 'Sign up', new_registration_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to 'Forgot your password?', new_password_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br>
  <% end %>
<% end %>